#!/usr/bin/env bash
# Write the tmux status theme from the active Omarchy palette.
# Missing keys, and a missing colors.toml, keep the sky colors the bar used before.
set -euo pipefail

out="${TMUX_STATUS_CONF:-$HOME/.local/state/tmux/status.conf}"
theme_file="${OMARCHY_THEME_COLORS:-${XDG_STATE_HOME:-$HOME/.local/state}/omarchy/current/theme/colors.toml}"

# Previous tmux-power "sky" palette.
fb_accent="#87ceeb"
fb_ink="#262626"
fb_muted="#626262"
fb_border="#444444"

pick() {
  local key="$1"
  local value=""
  if [[ -f "$theme_file" ]]; then
    value=$(sed -n -E "s/^${key}[[:space:]]*=[[:space:]]*[\"'](#[0-9A-Fa-f]{6})[\"'].*/\\1/p" "$theme_file" || true)
    value="${value%%$'\n'*}"
  fi
  printf '%s' "$value"
}

lum() {
  local hex="${1#\#}"
  local r g b
  r=$((16#${hex:0:2}))
  g=$((16#${hex:2:2}))
  b=$((16#${hex:4:2}))
  printf '%s' $(( (r * 299 + g * 587 + b * 114) / 1000 ))
}

# Ink for text drawn on the accent. Prefer whichever theme color contrasts more.
ink_for() {
  local accent="$1"
  local dark="$2"
  local light="$3"
  local la ld ll dd dl
  la=$(lum "$accent")
  ld=$(lum "$dark")
  ll=$(lum "$light")
  dd=$(( la > ld ? la - ld : ld - la ))
  dl=$(( la > ll ? la - ll : ll - la ))
  if (( dd >= dl )); then
    printf '%s' "$dark"
  else
    printf '%s' "$light"
  fi
}

accent=$(pick accent)
background=$(pick background)
foreground=$(pick foreground)
dim_foreground=$(pick dark_foreground)
dim_muted=$(pick muted)
secondary=$(pick magenta)
alert=$(pick red)

# Quiet text should stay readable on the theme background. Some light themes
# put the weaker contrast in dark_foreground, so take the stronger of the two.
text_muted=""
if [[ -n "$background" ]]; then
  best=-1
  for candidate in "$dim_foreground" "$dim_muted"; do
    [[ -n "$candidate" ]] || continue
    delta=$(( $(lum "$candidate") - $(lum "$background") ))
    (( delta < 0 )) && delta=$(( -delta ))
    if (( delta > best )); then
      best=$delta
      text_muted=$candidate
    fi
  done
fi
[[ -n "$text_muted" ]] || text_muted="$dim_foreground"

# Any theme key means the palette is in play. Missing keys keep the sky color.
if [[ -n "$accent$background$foreground$text_muted$dim_muted$secondary$alert" ]]; then
  [[ -n "$accent" ]] || accent="$fb_accent"
  [[ -n "$text_muted" ]] || text_muted="$fb_muted"
  border="${dim_muted:-$fb_border}"
  [[ -n "$secondary" ]] || secondary="$accent"
  [[ -n "$alert" ]] || alert="$accent"
  dark_candidate="${background:-$fb_ink}"
  light_candidate="${foreground:-#ffffff}"
  ink=$(ink_for "$accent" "$dark_candidate" "$light_candidate")
  body="${foreground:-default}"
else
  accent="$fb_accent"
  ink="$fb_ink"
  text_muted="$fb_muted"
  border="$fb_border"
  secondary="$fb_accent"
  alert="$fb_accent"
  body="default"
fi

mkdir -p "$(dirname "$out")"
tmp=$(mktemp "${out}.XXXXXX")
cat >"$tmp" <<EOF
# Generated by omarchy-status.sh. Do not edit.
set -g status-position bottom
set -g status-interval 1
set -g status-left-length 48
set -g status-right-length 72
set -g status-style "bg=default,fg=${text_muted}"
set -g status-bg default
set -g status-fg "${text_muted}"
set -g status-left-style "bg=default,fg=${body}"
set -g status-right-style "bg=default,fg=${body}"
set -gu @tmux_power_theme
set -gu @tmux_power_prefix_highlight_pos
set -gu @tmux_power_show_prefix
set -gu @tmux_power_show_date
set -gu @tmux_power_show_time
set -gu @tmux_power_date_format
set -gu @tmux_power_time_format
set -gu @tmux_power_show_upload_speed
set -gu @tmux_power_show_download_speed
set -gu @tmux_power_show_web_reachability
set -gu @tmux_power_show_nerdfont
set -gu @tmux_power_show_user
set -gu @tmux_power_show_host
set -gu @tmux_power_show_session
set -gu @prefix_highlight_show_copy_mode
set -gu @prefix_highlight_copy_mode_attr
set -gu @prefix_highlight_output_prefix
set -gu @prefix_highlight_output_suffix
set -g status-justify left
set -g status-left "#[fg=${body},bold] #S #[default]  "
set -g status-right "#{?client_prefix,#[fg=${secondary}]prefix ,}#{?window_zoomed_flag,#[fg=${secondary}]zoom ,}#{?pane_in_mode,#[fg=${secondary}]copy ,}#[fg=${body}]%r #[fg=${text_muted}]%a %b %d "
set -g window-status-separator ""
set -g window-status-format " #{?window_activity_flag,#[fg=${alert}],#{?window_last_flag,#[fg=${body}],#[fg=${text_muted}]}}#I #W "
set -g window-status-current-format "#[fg=${ink},bg=${accent},bold] #I #W #[default]"
set -g window-status-style "fg=${text_muted},bg=default,none"
set -g window-status-last-style "fg=${body},bg=default,none"
set -g window-status-activity-style "fg=${alert},bg=default,none"
set -g window-status-bell-style "fg=${ink},bg=${alert},bold"
set -g pane-border-style "fg=${border}"
set -g pane-active-border-style "fg=${accent}"
set -g message-style "bg=default,fg=${accent}"
set -g message-command-style "bg=default,fg=${accent}"
set -g mode-style "bg=${accent},fg=${ink}"
set -g clock-mode-colour "${accent}"
set -g display-panes-colour "${border}"
set -g display-panes-active-colour "${accent}"
EOF
mv "$tmp" "$out"
