windowrule = tile on, match:class ^(exefile.exe)$
windowrule = no_anim on, match:class ^(exefile.exe)$
windowrule = opaque on, match:class ^(exefile.exe)$
windowrule = immediate on, match:class ^(exefile.exe)$
windowrule = force_rgbx on, match:class ^(exefile.exe)$
windowrule = float off, match:class ^(exefile.exe)$
