# windowrulev2 = noinitialfocus,class:^(net-runelite-client-RuneLite)$,title:^win.*$
# windowrulev2 = stayfocused,class:^(net-runelite-client-RuneLite)$
windowrule = no_initial_focus on, match:class ^(net-runelite-client-RuneLite)$, match:title ^win.*$
# windowrule = stay_focused on, match:class ^(net-runelite-client-RuneLite)$
