
[env]
TERM = "xterm-256color"

[window]
# decorations = "None"
startup_mode = "Fullscreen"
# option_as_alt = "Both"
# my ultra wide doesn't like letting me see the last couple of pixesl :'(
padding = { x = 3, y = 0 }
[scrolling]
history = 100000

[font]
# normal = { family = "Fragment Mono", style = "Regular" }
# normal = { family = "Fira Code", style = "Regular" }
normal = { family = "Hack Nerd Font", style = "Regular" }
size = 13.0

[mouse]
hide_when_typing = true

[cursor]
# style = { shape = "Block", blinking = "On" }
# vi_mode_style = "Beam"

[keyboard]
bindings = [
  { key = "O", mods = "Command", action = "ToggleFullscreen"},
  # Unbind keys
  { key = "H", mods = "Command|Shift", action = "ReceiveChar" },
  { key = "K", mods = "Command", mode = "~Vi|~Search", action = "ReceiveChar" },
  { key = "K", mods = "Command", mode = "~Vi", action = "ReceiveChar" },
  { key = "K", mods = "Command", mode = "~Vi", action = "ReceiveChar" },
  { key = "N", mods = "Command", action = "ReceiveChar" },
  { key = "T", mods = "Command", action = "ReceiveChar" },
  { key = "F", mods = "Command|Control", action = "ReceiveChar" },
  { key = "F", mods = "Command", mode = "Search", action = "ReceiveChar" },
  { key = "B", mods = "Command", mode = "Search", action = "ReceiveChar" },
  { key = "Tab", mods = "Command", action = "ReceiveChar" },
  { key = "Tab", mods = "Command|Shift", action = "ReceiveChar" },
  { key = "[", mods = "Command|Shift", action = "ReceiveChar" },
  { key = "[", mods = "Command", action = "ReceiveChar" },
  { key = "]", mods = "Command|Shift", action = "ReceiveChar" },
  { key = "]", mods = "Command", action = "ReceiveChar" },
  { key = "1", mods = "Command", action = "ReceiveChar" },
  { key = "2", mods = "Command", action = "ReceiveChar" },
  { key = "3", mods = "Command", action = "ReceiveChar" },
  { key = "4", mods = "Command", action = "ReceiveChar" },
  { key = "5", mods = "Command", action = "ReceiveChar" },
  { key = "6", mods = "Command", action = "ReceiveChar" },
  { key = "7", mods = "Command", action = "ReceiveChar" },
  { key = "8", mods = "Command", action = "ReceiveChar" },
  { key = "9", mods = "Command", action = "ReceiveChar" },
]

[general]
live_config_reload = true

[terminal]
shell = { program = "/bin/zsh", args = ["--login"] }

# # TokyoNight Alacritty Colors
# # Default colors
# [colors.primary]
# background = '#24283b'
# foreground = '#c0caf5'
#
# #[colors.cursor]
# #cursor = '#c0caf5'
# #text = '#24283b'
#
# # Normal colors
# [colors.normal]
# black = '#1d202f'
# red = '#f7768e'
# green = '#9ece6a'
# yellow = '#e0af68'
# blue = '#7aa2f7'
# magenta = '#bb9af7'
# cyan = '#7dcfff'
# white = '#a9b1d6'
#
# # Bright colors
# [colors.bright]
# black = '#414868'
# red = '#f7768e'
# green = '#9ece6a'
# yellow = '#e0af68'
# blue = '#7aa2f7'
# magenta = '#bb9af7'
# cyan = '#7dcfff'
# white = '#c0caf5'
#
# # Indexed Colors
# [[colors.indexed_colors]]
# index = 16
# color = '#ff9e64'
#
# [[colors.indexed_colors]]
# index = 17
# color = '#db4b4b'
